CREATE TABLE BTCNTT3.HANGHANGKHONG
(
  MAHANG varchar2(2),
  TENHANG varchar2(50) not null,
  NGTL date not null,
  DUONGBAY number not null,
  CONSTRAINT PK_HANGHANGKHONG PRIMARY KEY(MAHANG)
);

CREATE TABLE BTCNTT3.CHUYENBAY
(
  MACB varchar2(5),
  MAHANG varchar2(2) not null,
  XUATPHAT varchar2(10) not null,
  DIEMDEN varchar2(10) not null,
  BATDAU date not null,
  TGBAY number(3,1),
  CONSTRAINT PK_CHUYENBAY PRIMARY KEY(MACB)
);

CREATE TABLE BTCNTT3.NHANVIEN
(
  MANV varchar2(4),
  HOTEN varchar2(50) not null,
  GIOITINH varchar2(3) not null,
  NGSINH date not null,
  NGVL date not null,
  CHUYENMON varchar(10),
  CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
);

CREATE TABLE BTCNTT3.PHANCONG
(
  MACB varchar2(5),
  MANV varchar2(4),
  NHIEMVU varchar2(20),
  CONSTRAINT PK_PHANCONG PRIMARY KEY(MACB, MANV)
);

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI';

INSERT INTO BTCNTT3.HANGHANGKHONG VALUES ('VN','Vietnam Airlines','15/01/1956','52');
INSERT INTO BTCNTT3.HANGHANGKHONG VALUES ('VJ','Vietjet Air','25/12/2011','33');
INSERT INTO BTCNTT3.HANGHANGKHONG VALUES ('BL','Jetstar Pacific Airlines','01/12/1990','13');

INSERT INTO BTCNTT3.CHUYENBAY VALUES ('VN550','VN','TP HCM','Singapore','20/12/2015 13:15','2');
INSERT INTO BTCNTT3.CHUYENBAY VALUES ('VJ331','VJ','Da Nang','Vinh','28/12/2015 22:30','1');
INSERT INTO BTCNTT3.CHUYENBAY VALUES ('BL696','BL','TP HCM','Da Lat','24/12/2015 06:00','0.5');

INSERT INTO BTCNTT3.NHANVIEN VALUES ('NV01','Lam Van Ben','Nam','10/09/1978','05/06/2000','Phi Cong');
INSERT INTO BTCNTT3.NHANVIEN VALUES ('NV02','Duong Thi Luc','Nu','22/03/1989','12/11/2013','Tiep Vien');
INSERT INTO BTCNTT3.NHANVIEN VALUES ('NV03','Hoang Thanh Tung','Nam','29/07/1983','11/04/2007','Tiep Vien');

INSERT INTO BTCNTT3.PHANCONG VALUES ('VN550','NV01','Co Truong');
INSERT INTO BTCNTT3.PHANCONG VALUES ('VN550','NV02','Tiep Vien');
INSERT INTO BTCNTT3.PHANCONG VALUES ('BL696','NV03','Tiep Vien Truong');

------------3----------

ALTER TABLE BTCNTT3.NHANVIEN ADD CONSTRAINT CHECK_3 CHECK (CHUYENMON='Phi Cong' or CHUYENMON='Tiep Vien');

------------4----------

CREATE OR REPLACE TRIGGER TRG_CB 
AFTER INSERT OR UPDATE
    ON BaiTapCNTT3.CHUYENBAY
    FOR EACH ROW
DECLARE 
    HHK_NGTL DATE;
BEGIN
    SELECT BaiTapCNTT3.HANGHANGKHONG.NGTL INTO HHK_NGTL
    FROM  BaiTapCNTT3.HANGHANGKHONG
    WHERE  BaiTapCNTT3.HANGHANGKHONG.MAHANG = :NEW.MAHANG;
    
    IF :NEW.BATDAU <= HHK_NGTL THEN
        RAISE_APPLICATION_ERROR (-20100, 'NGAY BAT DAU CUA CHUYEN BAY PHAI NHO HON NGAY THANH LAP CUA HANG');
    END IF;
END;



CREATE OR REPLACE TRIGGER TRG_HHK
AFTER UPDATE
    ON BaiTapCNTT3.HANGHANGKHONG
    FOR EACH  ROW
    
DECLARE 
    CB_BATDAU DATE;
        
BEGIN 
    SELECT BaiTapCNTT3.CHUYENBAY.BATDAU INTO CB_BATDAU
    FROM BaiTapCNTT3.CHUYENBAY
    WHERE BaiTapCNTT3.CHUYENBAY.MAHANG = :NEW.MAHANG AND
            BaiTapCNTT3.CHUYENBAY.BATDAU <= all  (SELECT CB.BATDAU  FROM  BaiTapCNTT3.CHUYENBAY CB
                                WHERE CB.MAHANG = :NEW.MAHANG);
                                
    IF :NEW.NGTL >= CB_BATDAU THEN
        RAISE_APPLICATION_ERROR (-20100, 'NGAY THANH LAP CUA HANG PHAI NHO HON NGAY BAT DAU CUA CHUYEN BAY');
    END IF;
END;

------------5----------

SELECT *
FROM BTCNTT3.NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH)=7;

------------6----------

SELECT BTCNTT3.CHUYENBAY.MACB
FROM BTCNTT3.CHUYENBAY, BTCNTT3.PHANCONG
WHERE CHUYENBAY.MACB=PHANCONG.MACB
GROUP BY BTCNTT3.CHUYENBAY.MACB
HAVING COUNT(PHANCONG.MANV) = (
  SELECT MAX(COUNT(PHANCONG.MANV))
  FROM BTCNTT3.CHUYENBAY, BTCNTT3.PHANCONG
  WHERE CHUYENBAY.MACB=PHANCONG.MACB
  GROUP BY BTCNTT3.CHUYENBAY.MACB
);

------------7----------

SELECT BTCNTT3.CHUYENBAY.MACB
FROM BTCNTT3.CHUYENBAY, BTCNTT3.PHANCONG
WHERE CHUYENBAY.MACB=PHANCONG.MACB and CHUYENBAY.XUATPHAT='Da Nang'
GROUP BY BTCNTT3.CHUYENBAY.MACB
HAVING COUNT(PHANCONG.MANV) < 2;

------------8----------

SELECT *
FROM BTCNTT3.NHANVIEN
WHERE NOT EXISTS (
  SELECT *
  FROM BTCNTT3.CHUYENBAY
  WHERE NOT EXISTS (
    SELECT *
    FROM BTCNTT3.PHANCONG
    WHERE PHANCONG.MACB=CHUYENBAY.MACB and PHANCONG.MANV=NHANVIEN.MANV
  )
);