--4. Ngay BAT DAU CHUYEN BAY LUON LON HON NGAY THANG LAP CUA HANG
CREATE OR REPLACE TRIGGER TRG_CB 
AFTER INSERT OR UPDATE
    ON BaiTapCNTT3.CHUYENBAY
    FOR EACH ROW
DECLARE 
    HHK_NGTL DATE;
BEGIN
    SELECT BaiTapCNTT3.HANGHANGKHONG.NGTL INTO HHK_NGTL
    FROM  BaiTapCNTT3.HANGHANGKHONG
    WHERE  BaiTapCNTT3.HANGHANGKHONG.MAHANG = :NEW.MAHANG;
    
    IF :NEW.BATDAU <= HHK_NGTL THEN
        RAISE_APPLICATION_ERROR (-20100, 'NGAY BAT DAU CUA CHUYEN BAY PHAI NHO HON NGAY THANH LAP CUA HANG');
    END IF;
END;




CREATE OR REPLACE TRIGGER TRG_HHK
AFTER UPDATE
    ON BaiTapCNTT3.HANGHANGKHONG
    FOR EACH  ROW
    
DECLARE 
    CB_BATDAU DATE;
        
BEGIN 
    SELECT BaiTapCNTT3.CHUYENBAY.BATDAU INTO CB_BATDAU
    FROM BaiTapCNTT3.CHUYENBAY
    WHERE BaiTapCNTT3.CHUYENBAY.MAHANG = :NEW.MAHANG AND
            BaiTapCNTT3.CHUYENBAY.BATDAU <= all  (SELECT CB.BATDAU  FROM  BaiTapCNTT3.CHUYENBAY CB
                                WHERE CB.MAHANG = :NEW.MAHANG);
                                
    IF :NEW.NGTL >= CB_BATDAU THEN
        RAISE_APPLICATION_ERROR (-20100, 'NGAY THANH LAP CUA HANG PHAI NHO HON NGAY BAT DAU CUA CHUYEN BAY');
    END IF;
END;