CREATE TABLE BAITAP2.USER1(
    U_ID VARCHAR2(9),
    USERNAME VARCHAR2(15) NOT NULL,
    PASS VARCHAR2(10) NOT NULL,
    REGDAY DATE NOT NULL ,
    NATIONALITY NVARCHAR2(20) NOT NULL,
    CONSTRAINT pk_USER1 PRIMARY KEY (U_ID)  
);

CREATE TABLE BAITAP2.CHANNEL(
    CHANNEL_ID VARCHAR2(4),
    CNAME VARCHAR2(15) NOT NULL,
    SUBCRIBES NUMBER NOT NULL,
    OWNNER NUMBER NOT NULL,
    CREATED DATE NOT NULL
    CONSTRAINT pk_CHANNEL PRIMARY KEY (CHANNEL_ID)
);

CREATE TABLE BAITAP2.VIDEO(
    VIDEO_ID VARCHAR2(10),
    TITLE NVARCHAR2(100) NOT NULL,
    DURATIONS NUMBER NOT NULL,
    AGE NUMBER NOT NULL,
    CONSTRAINT pk_VIDEO PRIMARY KEY (VIDEO_ID)
);

CREATE TABLE BAITAP2.SHARES(
    VIDEO_ID VARCHAR2(10)NOT NULL,
    CHANNEL_ID VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_SHARES PRIMARY KEY (VIDEO_ID, CHANNEL_ID)
);


INSERT INTO BAITAP2.USER1 VALUES('001', 'faptv', '123456abc', '01/01/2014', 'Viet Nam');
INSERT INTO BAITAP2.USER1 VALUES('002', 'kemxoitv', '@147869iii', '05/06/2015', 'Campuchia');
INSERT INTO BAITAP2.USER1 VALUES('003', 'openshare', 'qwertyuiop', '12/05/2009', 'Viet Nam');

INSERT INTO BAITAP2.CHANNEL VALUES('C120', 'FAP TV', '2343', '001', '02/01/2014');
INSERT INTO BAITAP2.CHANNEL VALUES('C905', 'Kem xôi TV', '1032', '002', '09/07/2015');
INSERT INTO BAITAP2.CHANNEL VALUES('C357', 'OpenShare Cáfe', '5064', '003', '10/12/2010');

INSERT INTO BAITAP2.VIDEO VALUES('V100229', 'FAPtv Com Nguoi T?p 41 - ?ot Nhap', '469', '18');
INSERT INTO BAITAP2.VIDEO VALUES('V211002', 'Kem xôi: Tap 31 - May Kool tình yêu cua anh', '312', '16');
INSERT INTO BAITAP2.VIDEO VALUES('V400002', 'Noi tình yêu ket thúc - Hoàng Tuan', '378', '0');

INSERT INTO BAITAP2.SHARES VALUES('V100229', 'C905');
INSERT INTO BAITAP2.SHARES VALUES('V211002', 'C120');
INSERT INTO BAITAP2.SHARES VALUES('V400002', 'C357');

--3. Hien thuc ràng buoc toàn ven sau: Ngày dang ký duoc mac dinh là ngày hien tai.
ALTER TABLE BAITAP2.USER ADD CONSTRAINT CHECK (REGDAY >= systime)

--5 Tìm tat ca các video có gioi han do tuoi tu 16 tro lên.
SELECT VIDEO.VIDEOID, AGE
FROM BAITAP2.VIDEO
WHERE AGE >= 16;

--6. Tìm kênh có so nguoi theo dõi nhieu nhat
SELECT BAITAP2.CHANNEL.CHANNELID
FROM BAITAP2.CHANNEL
WHERE SUBCRIBES = (
SELECT MAX(BAITAP2.CHANNEL.SUBCRIBES)
FROM BAITAP2.CHANNEL.CHANNEL
);

--7. Voi moi video có gioi han do tuoi là 18, thong kê so kênh dã chia se.
SELECT VIDEO.VIDEOID, COUNT(CHANNELID) Tong
FROM BAITAP2.SHARES, BAITAP2.VIDEO
WHERE VIDEO.VIDEOID = SHARES.VIDEOID AND AGE >=18
GROUP BY BAITAP2.VIDEO.VIDEOID;

--8. Tìm video duoc tat ca các kênh chia se
SELECT *
FROM BAITTAP2.SHARES
WHERE NOT EXISTS (
    SELECT *
    FROM BATITAP2.CHANNEL 
    WHERE NOT EXISTS (
        SELECT * 
        FROM BAITAP2.SHARES
        WHERE VIDEO.VIDEOID = SHARES.VIDEOID
        AND SHARES.CHANNELID = CHANNEL.CHANNELID
    )
);
