CREATE TABLE BAITAP3.HANGHANGKHONG(
  MAHANG varchar2(2),
  TENHANG varchar2(50) not null,
  NGTL date not null,
  DUONGBAY number not null,
  CONSTRAINT PK_HANGHANGKHONG PRIMARY KEY(MAHANG)
);

CREATE TABLE BAITAP3.CHUYENBAY(
  MACB varchar2(5),
  MAHANG varchar2(2) not null,
  XUATPHAT varchar2(10) not null,
  DIEMDEN varchar2(10) not null,
  BATDAU date not null,
  TGBAY number(3,1),
  CONSTRAINT PK_CHUYENBAY PRIMARY KEY(MACB)
);

CREATE TABLE BAITAP3.NHANVIEN(
  MANV varchar2(4),
  HOTEN varchar2(50) not null,
  GIOITINH varchar2(3) not null,
  NGSINH date not null,
  NGVL date not null,
  CHUYENMON varchar(10),
  CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
);

CREATE TABLE BAITAP3.PHANCONG(
  MACB varchar2(5),
  MANV varchar2(4),
  NHIEMVU varchar2(20),
  CONSTRAINT PK_PHANCONG PRIMARY KEY(MACB, MANV)
);

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI';

INSERT INTO BAITAP3.HANGHANGKHONG VALUES ('VN','Vietnam Airlines','15/01/1956','52');
INSERT INTO BAITAP3.HANGHANGKHONG VALUES ('VJ','Vietjet Air','25/12/2011','33');
INSERT INTO BAITAP3.HANGHANGKHONG VALUES ('BL','Jetstar Pacific Airlines','01/12/1990','13');

INSERT INTO BAITAP3.CHUYENBAY VALUES ('VN550','VN','TP HCM','Singapore','20/12/2015 13:15','2');
INSERT INTO BAITAP3.CHUYENBAY VALUES ('VJ331','VJ','Da Nang','Vinh','28/12/2015 22:30','1');
INSERT INTO BAITAP3.CHUYENBAY VALUES ('BL696','BL','TP HCM','Da Lat','24/12/2015 06:00','0.5');

INSERT INTO BAITAP3.NHANVIEN VALUES ('NV01','Lam Van Ben','Nam','10/09/1978','05/06/2000','Phi Cong');
INSERT INTO BAITAP3.NHANVIEN VALUES ('NV02','Duong Thi Luc','Nu','22/03/1989','12/11/2013','Tiep Vien');
INSERT INTO BAITAP3.NHANVIEN VALUES ('NV03','Hoang Thanh Tung','Nam','29/07/1983','11/04/2007','Tiep Vien');

INSERT INTO BAITAP3.PHANCONG VALUES ('VN550','NV01','Co Truong');
INSERT INTO BAITAP3.PHANCONG VALUES ('VN550','NV02','Tiep Vien');
INSERT INTO BAITAP3.PHANCONG VALUES ('BL696','NV03','Tiep Vien Truong');

--cau3--
ALTER TABLE BAITAP3.NHANVIEN ADD CONSTRAINT CHECK (CHUYENMON >= 'PHICONG') OR (CHUYENMON = 'TIEPVIEN');

--cau5-- 
SELECT *
FROM BAITAP3.NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH) = 7;

--CAU6--
SELECT BAITAP3.CHUYENBAY.MACB
FROM BAITAP3.CHUYENBAY, BAITAP3.PHANCONG
WHERE CHUYENBAY.MACB=PHANCONG.MACB
GROUP BY BAITAP3.CHUYENBAY.MACB
HAVING COUNT(PHANCONG.MANV) = (
    SELECT MAX(COUNT(PHANCONG.MANV))
    FROM BAITAP3.CHUYENBAY, BAITAP3.PHANCONG
    WHERE CHUYENBAY.MACB=PHANCONG.MACB
    GROUP BY BAITAP3.CHUYENBAY.MACB
);

--CAU7--
SELECT BAITAP3.CHUYENBAY.MACB
FROM BAITAP3.CHUYENBAY, BAITAP3.PHANCONG
WHERE CHUYENBAY.MACB=PHANCONG.MACB and CHUYENBAY.XUATPHAT='Da Nang'
GROUP BY BAITAP3.CHUYENBAY.MACB
HAVING COUNT(PHANCONG.MANV) < 2;

--CAU8--
SELECT *
FROM BAITAP3.NHANVIEN
WHERE NOT EXISTS (
    SELECT *
    FROM BAITAP3.CHUYENBAY
    WHERE NOT EXISTS (
        SELECT * 
        FROM BAITAP.PHANCONG
        WHERE NHAVIEN.MANV = PHANCONG.MANV
        AND  PHANCONG.MACB = CHUYENBAY.MACB
    )
);